"""
verify_syncthing.py — Diagnostics and validation tool for Syncthing desktop-to-mobile sync.

Validates:
1. Active profile folder structures (profiles/, jds/, output/, data/)
2. .stignore pattern safety (ignoring SQLite WAL, shm, cache files)
3. SQLite WAL database checkpoint status (flushing unflushed WAL records)
4. Local Syncthing REST API reachability (port 8384 or custom SYNCTHING_URL)
5. Android Termux environment permissions and directory mappings
"""

import os
import socket
import sys
import urllib.request
from typing import Any, Dict, List, Optional, Tuple

import cli_art
import db
import profile_paths
import theme


def check_directory_structure(profile: Optional[str] = None) -> List[Dict[str, Any]]:
    """Verifies that all four core sync directories exist for the active profile."""
    prof = profile or profile_paths.active_profile()
    root = profile_paths.PROJECT_ROOT

    required_dirs = profile_paths.sync_roots(prof)

    results = []
    for label, path in required_dirs:
        exists = os.path.isdir(path)
        if not exists:
            try:
                os.makedirs(path, exist_ok=True)
                results.append(
                    {
                        "name": f"Folder: {label}",
                        "status": "PASS",
                        "detail": f"Created missing directory {os.path.relpath(path, root)}",
                    }
                )
            except Exception as e:
                results.append(
                    {
                        "name": f"Folder: {label}",
                        "status": "FAIL",
                        "detail": f"Failed to create {os.path.relpath(path, root)}: {e}",
                    }
                )
        else:
            item_count = len(os.listdir(path))
            results.append(
                {
                    "name": f"Folder: {label}",
                    "status": "PASS",
                    "detail": f"Present ({item_count} items) at {os.path.relpath(path, root)}",
                }
            )
    return results


def check_stignore_rules() -> Dict[str, Any]:
    """Verifies .stignore presence and required exclusion patterns for SQLite WAL and caches."""
    root = profile_paths.PROJECT_ROOT
    stignore_path = os.path.join(root, ".stignore")

    critical_patterns = [
        "*.db-wal",
        "*.db-shm",
        "__pycache__",
    ]

    if not os.path.isfile(stignore_path):
        # Create default safe .stignore
        content = (
            "// Syncthing ignore file auto-generated by resume-builder\n"
            "(?d)*.db-wal\n"
            "(?d)*.db-shm\n"
            "(?d)*.db-journal\n"
            "(?d)__pycache__\n"
            "(?d)*.pyc\n"
            "(?d).pytest_cache\n"
            "(?d)node_modules\n"
            "(?d)output/*/tmp/\n"
            "(?d).DS_Store\n"
        )
        try:
            with open(stignore_path, "w", encoding="utf-8") as f:
                f.write(content)
            return {
                "name": "Syncthing .stignore file",
                "status": "PASS",
                "detail": "Created safe .stignore excluding SQLite WAL and temporary build caches.",
            }
        except Exception as e:
            return {
                "name": "Syncthing .stignore file",
                "status": "FAIL",
                "detail": f"Missing .stignore and could not create: {e}",
            }

    try:
        with open(stignore_path, "r", encoding="utf-8") as f:
            lines = f.read()
        missing = [p for p in critical_patterns if p not in lines]
        if missing:
            return {
                "name": "Syncthing .stignore file",
                "status": "WARN",
                "detail": f".stignore exists but missing recommended rules: {', '.join(missing)}",
            }
        return {
            "name": "Syncthing .stignore file",
            "status": "PASS",
            "detail": ".stignore present with all critical SQLite WAL and cache filters configured.",
        }
    except Exception as e:
        return {
            "name": "Syncthing .stignore file",
            "status": "FAIL",
            "detail": f"Error reading .stignore: {e}",
        }


def check_database_wal(profile: Optional[str] = None) -> Dict[str, Any]:
    """Flushes SQLite WAL records directly into data.db to ensure sync consistency."""
    try:
        db.checkpoint(profile)
        db_path = db.get_db_path(profile)
        size_kb = os.path.getsize(db_path) / 1024.0 if os.path.exists(db_path) else 0
        return {
            "name": "SQLite Database WAL Checkpoint",
            "status": "PASS",
            "detail": f"WAL flushed cleanly to data.db ({size_kb:.1f} KB ready for atomic sync)",
        }
    except Exception as e:
        return {
            "name": "SQLite Database WAL Checkpoint",
            "status": "FAIL",
            "detail": f"Checkpoint failed: {e}",
        }


def check_syncthing_service() -> Dict[str, Any]:
    """Checks if local Syncthing daemon is actively listening on localhost:8384."""
    url = os.environ.get("SYNCTHING_URL", "http://127.0.0.1:8384")
    host = "127.0.0.1"
    port = 8384

    # Fast socket probe
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(1.0)
    result = sock.connect_ex((host, port))
    sock.close()

    if result == 0:
        return {
            "name": "Syncthing Service Status",
            "status": "PASS",
            "detail": f"Syncthing Web GUI/API is active and listening on {url}",
        }
    else:
        return {
            "name": "Syncthing Service Status",
            "status": "INFO",
            "detail": f"Syncthing daemon not active on port {port} (start Syncthing app or binary when syncing)",
        }


def check_termux_mobile_environment() -> Dict[str, Any]:
    """Detects whether running inside Termux on Android and validates termux-open."""
    is_termux = os.path.isdir("/data/data/com.termux") or "TERMUX_VERSION" in os.environ
    if not is_termux:
        return {
            "name": "Mobile Environment Check",
            "status": "PASS",
            "detail": "Desktop host environment verified (macOS/Linux/WSL).",
        }

    # Check termux-open for PDF rendering hook
    has_termux_open = any(
        os.path.isfile(os.path.join(p, "termux-open"))
        for p in os.environ.get("PATH", "").split(os.pathsep)
    )

    if has_termux_open:
        return {
            "name": "Mobile Environment Check",
            "status": "PASS",
            "detail": "Android Termux detected; termux-open available for native PDF viewing.",
        }
    else:
        return {
            "name": "Mobile Environment Check",
            "status": "WARN",
            "detail": "Termux detected, but 'termux-api' package not installed (run: pkg install termux-api).",
        }


def run_all_syncthing_checks(profile: Optional[str] = None) -> List[Dict[str, Any]]:
    """Runs all Syncthing verification checks and returns structured results."""
    checks = []
    checks.extend(check_directory_structure(profile))
    checks.append(check_stignore_rules())
    checks.append(check_database_wal(profile))
    checks.append(check_syncthing_service())
    checks.append(check_termux_mobile_environment())
    return checks


def render_syncthing_report(profile: Optional[str] = None) -> bool:
    """Renders a Rich terminal HUD with check statuses."""
    checks = run_all_syncthing_checks(profile)

    cli_art.console.print()
    cli_art.console.print(
        f"[{theme.BRAND}]› resume-builder — Syncthing Desktop/Mobile Verification[/]"
    )
    cli_art.console.print()

    from rich.table import Table

    tbl = Table(
        show_header=True,
        header_style=f"bold {theme.BRAND}",
        title="[bold]Syncthing Desktop-to-Mobile Sync Verification[/bold]",
        title_style=theme.BRAND_ACCENT,
        border_style=theme.BRAND,
    )
    tbl.add_column("Diagnostic Check", style="bold", width=36)
    tbl.add_column("Status", width=10)
    tbl.add_column("Detail", style="dim")

    all_pass = True
    for c in checks:
        st = c["status"]
        if st == "PASS":
            status_badge = f"[{theme.SUCCESS}]✓ PASS[/]"
        elif st == "WARN":
            status_badge = f"[{theme.WARNING}]⚠ WARN[/]"
        elif st == "INFO":
            status_badge = f"[{theme.INFO}]ℹ INFO[/]"
        else:
            status_badge = f"[{theme.ERROR}]✗ FAIL[/]"
            all_pass = False

        tbl.add_row(c["name"], status_badge, c["detail"])

    cli_art.console.print(tbl)
    cli_art.console.print()

    if all_pass:
        cli_art.console.print(
            f"[{theme.SUCCESS}]✓ Sync environment is healthy and ready for seamless desktop/mobile pairing.[/]\n"
        )
    else:
        cli_art.console.print(
            f"[{theme.WARNING}]⚠ One or more sync checks require attention before syncing.[/]\n"
        )
    return all_pass


if __name__ == "__main__":
    prof = sys.argv[1] if len(sys.argv) > 1 else None
    success = render_syncthing_report(prof)
    sys.exit(0 if success else 1)
